### ISSUE TITLE
A way to use custom incomplete tokens

### ISSUE THREAD

**Issue by prometh07** [piotrmurach/tty-progressbar#19]
Let's say I have a bunch of things to compute. If a computation fails, I'd like to show its result in the associated progressbar. For example:

```
files = ['file1', 'file2']
bar = TTY::ProgressBar.new("Downloading: [:bar]", total: files.size)
files.each do |f|
  result = download_file(f)
  result_token = result ? '.' : 'x'
  bar.advance(1, result_token)
end
```
A possible output:
```
Downloading: [. ]
Downloading: [.x]
```

I can make a PR if you find the idea useful.

**Comment by piotrmurach** [comment]
Have you looked at [custom tokens](https://github.com/piotrmurach/tty-progressbar#33-custom-tokens)?

**Comment by piotrmurach** [comment]
The problem with achieving what you have specified lies in the way the progress bar is rendered. You only have `:complete` and `:incomplete` tokens. Your case of downloading multiple files and displaying `[...x....x...x]` is actually impossible to achieve. The reason is that the progress bar is constantly repainted, so even if during current progress you would update the display to show `x` it would be wiped out in another iteration and replaced with `:complete` character whatever it may be.

To achieve your behaviour I would suggest using [tty-spinner](https://github.com/piotrmurach/tty-spinner) which is more suitable to downloading files due to their indeterminate size. I have even added [files download example](https://github.com/piotrmurach/tty-spinner/blob/master/examples/multi/files.rb) which shows a check mark for successful downloads and cross for failed ones.

If you're really adamant that you want to use this progress bar then in your case I would create multi progressbar and mark failure on each progress bar separately. For example,

```ruby
multibar = TTY::ProgressBar::Multi.new
threads = []
files.each do |file|
  bar = multibar.register "downloading #{file.name} [:bar]", total: file.size, head: '>' 
  threads << Thread.new { 
   if file.failed? 
     bar.update(head: 'x')
     bar.stop
   else
      bar.advance
   end
  }
end
```
which could result in:
```
downloading file1 [=============]
downloading file2 [=========x   ] # marks failed download and stops
```
