### ISSUE TITLE
When using `hide_cursor`, it remains hidden on premature exit

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-progressbar#40]
### Issue

When using `hide_cursor`, if the user presses <kbd>Ctrl</kbd>+<kbd>C</kbd> (or the progress bar is otherwise interrupted prematurely), then the cursor stays hidden.

One workaround I found, is to call `bar.stop` in some ensure block, like so:

```ruby
require 'tty-progressbar'

begin
  bar = TTY::ProgressBar.new("downloading [:bar]", total: 30, hide_cursor: true)
  
  30.times do
    sleep(0.1)
    bar.advance(1)
  end

ensure
  bar.stop

end
```

But this feels like it should be the library's responsibility, not the user's.

### Reproduction steps

Run this, and press <kbd>Ctrl</kbd>+<kbd>C</kbd> before it finishes.

```ruby
require 'tty-progressbar'
bar = TTY::ProgressBar.new("downloading [:bar]", total: 30, hide_cursor: true)
  
30.times do
  sleep(0.1)
  bar.advance(1)
end
```

### Actual behaviour

The cursor stays hidden after termination.

### Expected behaviour

The cursor should revert to its visible state after termination.

### Proposed solution

Perhaps something along these lines can work? 

Change this:

https://github.com/piotrmurach/tty-progressbar/blob/a662108eab2eb078cfd40fb014210c92a9169d27/lib/tty/progressbar.rb#L272-L276

to this:

```ruby
       if hide_cursor && @last_render_width == 0 && !(@current >= total)
         write(TTY::Cursor.hide)
+        at_exit { stop }
       end
```

There is probably a better candidate than `at_exit`, but this is the simplest idea I could come up with.

**Comment by piotrmurach** [comment]
Hi Danny,

Thanks for reporting this issue.

I'm not 100% sure that's the responsibility of `tty-progressbar` to clean up cursor after an exit. The exit may be due to reasons outside of progress bar scope, for example, during the thread sleep time. So the boundary of what is and isn't the responsibility of `tty-progressbar` is a bit blurry.  This is why, by default, the cursor isn't hidden.

I used the `at_exit` in the past for this kind of clean up but there are other issues with it, if my memory serves me right, this callback doesn't work with forked/child processes etc... Exit is a kind of extreme situation and I kind of wouldn't expect the progress bar to stop nicely. However, I can totally see the utility of using the `at_exit` callback, especially with a hidden cursor. It's annoying when it disappears. 

So what I'm thinking about is provide more documentation for the hidden cursor option. Also, we could add the ensure to `advance` or `render` methods. What do you think?

**Comment by DannyBen** [comment]
Yes, well - I totally agree that `at_exit` is overreaching and too extreme. It was just the first quick and dirty hack I could find to demonstrate the expected behavior.

That said, I do not think that adding documentation on how to unhide the cursor is the best way to approach it. How I see it, it *is* the progress bar's responsibility to revert all permanent changes - such as colors, and cursor modifications - to their original state.

This is especially true, since the progress bar - by nature - will almost always run alongside long-running operations, which scream to be Ctrl+C'ed.

I was hoping this could be fixed by using some `ensure` block (in the gem, not by the user). If that is the case, this is definitely the best approach.

**Comment by piotrmurach** [comment]
I'd like to resolve this issue before a new release.

Here are a few possible solutions that I can see:

1. Use `trap` to catch the interrupt/termination signal and clear the hidden cursor. This is problematic for a few reasons. Trapping signal means that the 'real' place of failure is masked. If the Interrupt failure is raised then the original location of the failure is lost. No matter how much I tried this solution(including passed uses in this gem) it brings plenty of issues.

2. Use `at_exit` to catch the interrupt. This is better than the `trap` in so far that it doesn't obfuscate the error. Equally, this is not guaranteed to be triggered at all. For me `at_exit` is a reasonable utility for any program to clean up it's state before it exists. However, for a utility like `tty-progressbar` it feels inappropriate to be using it.

3. Use `ensure` to show the hidden cursor. Unfortunately due to the iterative nature of rendering using ensure during each render call would keep on showing and hiding cursor on every call like `advance`. This would introduce flickers on terminals. The only sensible place to have `ensure` statement, in this case, is in the `stop` and `finish` calls. Even if I decided to add ensure statement to each render, the interrupt call may and probably will happen outside of progress bar instance scope. For example, during the `sleep`.

Originally, I decided to not hide the cursor by default as there are many issues with doing so. Equally, I wanted to provide this ability to people who want to use it to make the UI experience a bit smoother. The more I think about it the more I feel that for any application code the most reasonable approach is to do what you suggested in your example or use the `at_exit` callback. I also think that having an explanation in the readme would suffice. Nobody will know about the option unless they read the docs and when they do so, they will find the section that will explain potential pitfalls and how to deal with them. Maybe even use the combination of the two.
