### ISSUE TITLE
[Feature]add alignment column before the bar show

### ISSUE THREAD

**Issue by icai** [piotrmurach/tty-progressbar#46]
### Feature

can support add alignment column before the bar show?

as the following picture:

![image](https://user-images.githubusercontent.com/1061012/99900777-97771580-2cec-11eb-8b7c-8ee2ee8f4652.png)

https://unix.stackexchange.com/questions/396223/bash-shell-script-output-alignment

**Comment by piotrmurach** [comment]
Hi Terry,

Thanks for using the `tty-progresbar`. 

You're in full control how you format your progress bar display. You can create column alignment using string formatting characters so that each progress bar will have the same width for IP address like so:

```ruby
TTY::Progressbar("Network %-12s : :bar" % [IP address string], total: ...)
```

The same goes for multi progress bars. You register each bar with different IP address but the same format string as shown above.

**Comment by icai** [comment]
thanks, oh, Is ruby string format:sweat_smile: @piotrmurach
